"""Write or check the SHA-256 manifests of the source and build inputs."""
from pathlib import Path
import argparse
import hashlib

ROOT = Path(__file__).resolve().parents[1]
SUFFIXES = {".py", ".cpp", ".hpp", ".h"}


def source_files(directory):
    return {p for p in directory.rglob("*") if p.is_file() and p.suffix in SUFFIXES
            and "__pycache__" not in p.parts}


def core_inputs():
    paths = {ROOT / name for name in ("pyproject.toml", "setup.py", "_build_support.py", "MANIFEST.in",
                                      "vendor/CORE_HEADERS.txt", "ci/install_boost_headers.sh")}
    for name in ("qfcore", "qfops", "qfnext"):
        paths |= source_files(ROOT / "src" / name)
    paths |= {ROOT / "vendor/gudhi_include" / name for name in
              (ROOT / "vendor/CORE_HEADERS.txt").read_text().splitlines() if name}
    return paths


def manifest(paths):
    rows = ["# SHA256 of QF source/build inputs; generated by tools/build_provenance.py\n"]
    for path in sorted(paths, key=lambda p: p.relative_to(ROOT).as_posix()):
        if not path.is_file():
            raise RuntimeError(f"Missing build input: {path.relative_to(ROOT)}")
        rows.append(hashlib.sha256(path.read_bytes()).hexdigest() + "  " + path.relative_to(ROOT).as_posix() + "\n")
    return "".join(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail rather than update stale manifests")
    args = parser.parse_args()
    jobs = [(ROOT / "src/qfcore/_build_inputs.sha256", core_inputs())]
    failures = []
    for target, inputs in jobs:
        expected = manifest(inputs)
        label = target.relative_to(ROOT)
        if args.check:
            if not target.is_file() or target.read_text() != expected:
                failures.append(str(label))
            else:
                print(f"OK {label} ({len(inputs)} inputs)")
        else:
            target.write_text(expected, encoding="utf-8")
            print(f"Wrote {label} ({len(inputs)} inputs)")
    if failures:
        parser.exit(1, "Stale build provenance: " + ", ".join(failures) + "\nRun python tools/build_provenance.py\n")


if __name__ == "__main__":
    main()
